import type { Metadata } from "next";
import "./styles/main.scss";
import { ThemeProvider } from "@/components/ThemeProvider";

import { Header } from "@/components/sections/Header";
import { Footer } from "@/components/sections/Footer";
import { poppins, balooBhaijaan2, nunitoSans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isGrayscale = false;

  return (
    <html
      lang="es"
      suppressHydrationWarning
      style={{ filter: isGrayscale ? "grayscale(100%)" : "none" }}
    >
      <body
        className={`${poppins.variable} ${balooBhaijaan2.variable} ${nunitoSans.variable} font-sans antialiased min-h-screen bg-surface-light text-text-light dark:bg-surface-dark dark:text-text-dark`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
